src/CI/AppBundle/Entity/Build.php
<?php

namespace CI\AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Criteria;

/**
 * Build
 */
class Build
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var array
     */
    private $response;

    /**
     * @var string
     */
    private $script;

    /**
     * @var string
     */
    private $branch;

    /**
     * @var string
     */
    private $repo;

    /**
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @var Type
     */
    private $statusType;

    /**
     * @var User
     */
    private $createdBy;

    /**
     * @var User
     */
    private $updatedBy;

    /**
     * @var ArrayCollection
     */
    private $buildUpload;

    /**
     * @var ArrayCollection
     */
    private $tag;

    /**
     * @var boolean
     */
    private $autoDeploy;

    /**
     * @var Application
     */
    private $application;
    
    public function __construct()
    {
        $this->createdAt = new \DateTime;
        $this->updatedAt = new \DateTime;
        $this->buildUpload = new ArrayCollection;
        $this->tag = new ArrayCollection;
        $this->autoDeploy = false;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set response
     *
     * @param array $response
     *
     * @return Build
     */
    public function setResponse(array $response)
    {
        $this->response = $response;

        return $this;
    }

    /**
     * Get response
     *
     * @return array
     */
    public function getResponse()
    {
        return $this->response;
    }

    /**
     * Set script
     *
     * @param string $script
     *
     * @return Build
     */
    public function setScript($script)
    {
        $this->script = $script;

        return $this;
    }

    /**
     * Get script
     *
     * @return string
     */
    public function getScript()
    {
        return $this->script;
    }

    /**
     * Set branch
     *
     * @param string $branch
     *
     * @return Build
     */
    public function setBranch($branch)
    {
        $this->branch = $branch;

        return $this;
    }

    /**
     * Get branch
     *
     * @return string
     */
    public function getBranch()
    {
        return $this->branch;
    }

    /**
     * Set repo
     *
     * @param string $repo
     *
     * @return Build
     */
    public function setRepo($repo)
    {
        $this->repo = $repo;

        return $this;
    }

    /**
     * Get repo
     *
     * @return string
     */
    public function getRepo()
    {
        return $this->repo;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return Build
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     *
     * @return Build
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set statusType
     *
     * @param Type $statusType
     *
     * @return Build
     */
    public function setStatusType(Type $statusType = null)
    {
        $this->statusType = $statusType;

        return $this;
    }

    /**
     * Get statusType
     *
     * @return Type
     */
    public function getStatusType()
    {
        return $this->statusType;
    }

    /**
     * Set createdBy
     *
     * @param User $createdBy
     *
     * @return Build
     */
    public function setCreatedBy(User $createdBy = null)
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    /**
     * Get createdBy
     *
     * @return User
     */
    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * Set updatedBy
     *
     * @param User $updatedBy
     *
     * @return Build
     */
    public function setUpdatedBy(User $updatedBy = null)
    {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    /**
     * Get updatedBy
     *
     * @return User
     */
    public function getUpdatedBy()
    {
        return $this->updatedBy;
    }

    /**
     * Add buildUpload
     *
     * @param BuildUpload $buildUpload
     *
     * @return Build
     */
    public function addBuildUpload(BuildUpload $buildUpload)
    {
        if (false === $this->buildUpload->contains($buildUpload)) {
            $buildUpload->setBuild($this);
            $this->buildUpload[] = $buildUpload;
        }

        return $this;
    }

    /**
     * @return BuildUpload|ArrayCollection
     */
    public function getBuildUpload()
    {
        return $this->buildUpload;
    }

    /**
     * Remove buildUpload
     *
     * @param BuildUpload $buildUpload
     */
    public function removeBuildUpload(BuildUpload $buildUpload)
    {
        $this->buildUpload->removeElement($buildUpload);
    }

    /**
     * Add tag
     *
     * @param Tag $tag
     *
     * @return Build
     */
    public function addTag(Tag $tag)
    {
        if (false === $this->tag->contains($tag)) {
            $tag->setBuild($this);
            $this->tag->add($tag);
        }

        return $this;
    }

    /**
     * @return Tag|ArrayCollection
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Remove tag
     *
     * @param Tag $tag
     */
    public function removeTag(Tag $tag)
    {
        $this->tag->removeElement($tag);
    }

    /**
     * Set autoDeploy
     *
     * @param boolean $autoDeploy
     *
     * @return Build
     */
    public function setAutoDeploy($autoDeploy)
    {
        $this->autoDeploy = $autoDeploy;

        return $this;
    }

    /**
     * Get autoDeploy
     *
     * @return boolean
     */
    public function getAutoDeploy()
    {
        return $this->autoDeploy;
    }

    /**
     * Set application
     *
     * @param Application $application
     *
     * @return Build
     */
    public function setApplication(Application $application = null)
    {
        if (null !== $application) {
            $application->setBuild($this);
        }

        $this->application = $application;

        return $this;
    }

    /**
     * Get application
     *
     * @return Application
     */
    public function getApplication()
    {
        return $this->application;
    }

    /**
     * @return null|Tag
     */
    public function getCurrentTag()
    {
        $tags = $this->tag->toArray();

        usort($tags, function(Tag $left, Tag $right) {
           return $left->getId() > $right->getId() ? -1 : 1;
        });

        return reset($tags);
    }

    /**
     * @return null|string
     */
    public function getCurrentTagName()
    {
        $tag = $this->getCurrentTag();

        if (false === $tag instanceof Tag) {
            return null;
        }

        return $tag->getName();
    }

    /**
     * @return null|string
     */
    public function getCurrentTagCommit()
    {
        $tag = $this->getCurrentTag();

        if (false === $tag instanceof Tag) {
            return null;
        }

        return $tag->getCommit();
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return sprintf('BUILD %s', $this->getId());
    }
}

src/CI/AppBundle/Form/BuildType.php
<?php

namespace CI\AppBundle\Form;

use CI\AppBundle\Entity\Application;
use CI\AppBundle\Entity\Build;
use CI\AppBundle\Repository\ApplicationRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotNull;

class BuildType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('application', EntityType::class, [
            'class' => Application::class,
            'label' => 'trans.entity.application',
            'placeholder' => 'trans.message.choose_an_option',
            'query_builder' => function (ApplicationRepository $repo) {
                return $repo->getAvailableAsQueryBuilder();
            }
        ]);

        $builder->add('branch', TextType::class, [
            'label' => 'trans.entity.branch',
            'constraints' => new NotNull(),
        ]);

        $builder->add('repo', TextType::class, [
            'label' => 'trans.entity.repo',
            'constraints' => new NotNull(),
        ]);

        $builder->add('script', TextareaType::class, [
            'label' => 'trans.entity.script',
        ]);

        $builder->add('autoDeploy', ChoiceType::class, [
            'label' => 'trans.entity.autoDeploy',
            'choices' => [
                'trans.message.no' => 0,
                'trans.message.yes' => 1,
            ]
        ]);

        $builder->add('buildUpload', CollectionType::class, [
            'label' => 'trans.entity.upload',
            'allow_add' => true,
            'allow_delete' => true,
            'prototype' => true,
            'by_reference' => false,
            'entry_type' => BuildUploadType::class
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Build::class,
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'ci_appbundle_build';
    }


}

src/CI/AppBundle/Controller/BuildController.php
<?php

namespace CI\AppBundle\Controller;

use CI\AppBundle\Entity\Build;
use CI\AppBundle\Entity\BuildUpload;
use CI\AppBundle\Form\BuildType;
use CI\AppBundle\Repository\BuildRepository;
use CI\AppBundle\Service\Pagination\Pagination;
use CI\AppBundle\Twig\MessageExtension;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class BuildController extends Controller
{
    public function indexAction($page)
    {
        $pagination = $this->getDoctrine()
            ->getManager()
            ->getRepository('CIAppBundle:Build')
            ->getPagination($this->getUser(), $page);

        $pagination->set(Pagination::ROUTE, 'ci_app_build_index');

        return $this->render('CIAppBundle:Build:index.html.twig', [
            'pagination' => $pagination
        ]);
    }

    public function showAction(Build $build)
    {
        return $this->render('CIAppBundle:Build:show.html.twig', [
            'build' => $build,
            'response' => var_export($build->getResponse(), true)
        ]);
    }

    public function createAction(Request $request)
    {
        /** @var BuildRepository $repo */
        $repo = $this->getDoctrine()->getRepository(Build::class);

        $form = $this->createForm(BuildType::class);

        $form->handleRequest($request);

        if ('POST' === $request->getMethod() && true === $form->isValid()) {
            $this->get('session')->getFlashBag()->add(MessageExtension::SUCCESS, 'trans.message.created');
            $build = $repo->create($form->getData(), $this->getUser());

            return $this->redirectToRoute('ci_app_build_show', ['build' => $build->getId()]);
        }

        return $this->render('CIAppBundle:Build:create.html.twig', [
            'form' => $form->createView()
        ]);
    }

    public function editAction(Request $request, Build $build)
    {
        $form = $this->createForm(BuildType::class, $build);

        $form->handleRequest($request);

        if ('POST' === $request->getMethod() && true === $form->isValid()) {
            $this->get('session')->getFlashBag()->add(MessageExtension::SUCCESS, 'trans.message.edited');
            $this->getDoctrine()->getRepository(Build::class)->edit($form->getData(), $this->getUser());

            return $this->redirectToRoute('ci_app_build_show', ['build' => $build->getId()]);
        }

        return $this->render('CIAppBundle:Build:edit.html.twig', [
            'form' => $form->createView(),
            'build' => $build,
        ]);
    }

    public function deleteAction(Build $build)
    {
        try {
            $this->getDoctrine()->getRepository(Build::class)->delete($build, $this->getUser());

            $this->get('session')->getFlashBag()->add(MessageExtension::SUCCESS, 'trans.message.deleted');

        } catch (\Exception $e) {
            $this->get('session')->getFlashBag()->add(MessageExtension::ERROR, $this->get('translator')->trans($e->getMessage()));
        }

        return $this->redirectToRoute('ci_app_build_index');
    }

    public function buildAction(Build $build)
    {
        try {
            $this->getDoctrine()->getRepository(Build::class)->build($build, $this->getUser());

        } catch (\Exception $e) {
            $this->get('session')->getFlashBag()->add(MessageExtension::ERROR, $e->getMessage());
        }

        return $this->redirectToRoute('ci_app_build_show', ['build' => $build->getId()]);
    }

    public function showBuildUploadAction(BuildUpload $buildUpload)
    {
        return $this->render('CIAppBundle:Build:show.build.upload.html.twig', [
            'buildUpload' => $buildUpload,
        ]);
    }
}

src/CI/AppBundle/Resources/views/Build/actions.html.twig
{% if show is not defined %}
    {% set show = false %}
{% endif %}

{% if show and is_granted('ROLE_BUILD_SHOW') %}
    <a title="{{ 'trans.action.show' | trans }}" class="btn btn-info" href="{{ path('ci_app_build_show', {build: build.id}) }}" role="button">
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
    </a>

{% endif %}

{% if BUILD_can_edit(build) %}
    <a title="{{ 'trans.action.edit' | trans }}" class="btn btn-info" href="{{ path('ci_app_build_edit', {build: build.id}) }}" role="button">
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    </a>

{% endif %}

{% if BUILD_can_build(build) %}
    <a title="{{ 'trans.action.build' | trans }}" class="btn btn-primary" href="{{ path('ci_app_build_build', {build: build.id}) }}" role="button">
        <span class="glyphicon glyphicon-send" aria-hidden="true"></span>
    </a>

{% endif %}

{% if BUILD_can_delete(build) %}
    <a onclick="return confirm('{{ 'trans.message.are.you.sure.delete' | trans}}');" title="{{ 'trans.action.delete' | trans }}" class="btn btn-danger" href="{{ path('ci_app_build_delete', {build: build.id}) }}" role="button">
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
    </a>

{% endif %}

src/CI/AppBundle/Resources/views/Build/create.html.twig
{% extends 'CIAppBundle::Default/crud/create.html.twig' %}

{% block title %}{{ 'trans.menu.build' | trans }}{% endblock %}

{% set form_action = path('ci_app_build_create') %}
{% set back = path('ci_app_build_index') %}

{% block form_left %}
    <h2><span class="glyphicon glyphicon-th-list"></span> {{ 'trans.title.properties' | trans }}</h2>

    {{ form_row(form.application) }}
    {{ form_row(form.branch) }}
    {{ form_row(form.repo) }}
    {{ form_row(form.script) }}
    {{ form_row(form.autoDeploy) }}

{% endblock %}

{% block form_right %}
    <div class="row">
        <div class="col-xs-6">
            <h2>
                <span class="glyphicon glyphicon-upload"></span>
                {{ 'trans.title.upload' | trans }}
                <a href="#" onclick="return false;" class="btn btn-xs btn-info" id="add-upload">{{ 'trans.action.add' | trans }}</a>
            </h2>

            {% form_theme form.buildUpload 'CIAppBundle::Build/form.theme.upload.html.twig' %}

            <table class="table table-striped table-bordered last">
                <thead>
                <tr>
                    <th>{{ "trans.entity.targetPath" | trans }}</th>
                    <th>{{ "trans.entity.value" | trans }}</th>
                    <th>-</th>
                </tr>
                </thead>
                <tbody id="upload">
                    {{ form_widget(form.buildUpload) }}
                </tbody>
            </table>
        </div>
    </div>


{% endblock %}

{% block javascripts %}
    {% include 'CIAppBundle::Build/form.javascript.html.twig' %}

{% endblock %}

src/CI/AppBundle/Resources/views/Build/edit.html.twig
{% extends 'CIAppBundle::Default/crud/create.html.twig' %}

{% block title %}{{ 'trans.menu.build' | trans }}{% endblock %}

{% set form_action = path('ci_app_build_edit', {build: build.id}) %}
{% set back = path('ci_app_build_index') %}

{% block form_left %}
    <h2><span class="glyphicon glyphicon-th-list"></span> {{ 'trans.title.properties' | trans }}</h2>

    {{ form_row(form.application) }}
    {{ form_row(form.branch) }}
    {{ form_row(form.repo) }}
    {{ form_row(form.script) }}
    {{ form_row(form.autoDeploy) }}

{% endblock %}

{% block form_right %}
    <div class="row">
        <div class="col-xs-6">
            <h2>
                <span class="glyphicon glyphicon-upload"></span>
                {{ 'trans.title.upload' | trans }}
                <a href="#" onclick="return false;" class="btn btn-xs btn-info" id="add-upload">{{ 'trans.action.add' | trans }}</a>
            </h2>

            {% form_theme form.buildUpload 'CIAppBundle::Build/form.theme.upload.html.twig' %}

            <table class="table table-striped table-bordered last">
                <thead>
                <tr>
                    <th>{{ "trans.entity.targetPath" | trans }}</th>
                    <th>{{ "trans.entity.value" | trans }}</th>
                    <th>-</th>
                </tr>
                </thead>
                <tbody id="upload">
                {{ form_widget(form.buildUpload) }}
                </tbody>
            </table>
        </div>
    </div>


{% endblock %}

{% block javascripts %}
    {% include 'CIAppBundle::Build/form.javascript.html.twig' %}

{% endblock %}

src/CI/AppBundle/Resources/views/Build/form.javascript.html.twig
{% javascripts '@CIAppBundle/Resources/public/js/collection.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
{% endjavascripts %}

<script type="text/javascript">
    $(function() {
        var upload = new Collection();
        upload.holder = $('#upload');
        upload.childTemplate = $('#ci_appbundle_build_buildUpload').attr('data-prototype');
        upload.load();

        $('#add-upload').click(function(e) {
            upload.createEmptyChild();
        });

        updateIndex = function(e, ui) {
            $('td.position', ui.item.parent()).each(function (i) {
                $(this).find('input').val(i + 1);
            });
        };

        $(".sort tbody").sortable({
            stop: updateIndex,
            delay: 150
        }).enableSelection();
    });

</script>

src/CI/AppBundle/Resources/views/Build/form.theme.upload.html.twig
{% block form_row %}
    <tr>
        <td>
            {{ form_widget(form.targetPath) }}
            {{ form_errors(form.targetPath) }}
        </td>
        <td>
            {{ form_widget(form.value) }}
            {{ form_errors(form.value) }}
        </td>
        <td>
            <a href="javascript:void(0);">
                <i class="glyphicon glyphicon-remove"></i>
            </a>
        </td>
    </tr>

{% endblock form_row %}

src/CI/AppBundle/Resources/views/Build/index.html.twig
{% extends 'CIAppBundle::Default/crud/index.html.twig' %}

{% block title %}{{ 'trans.menu.build' | trans }}{% endblock %}

{% block action %}
    {% if is_granted('ROLE_BUILD_CREATE') %}
        <p>
            <a title="{{ 'trans.action.add' | trans }}" href="{{ path('ci_app_build_create') }}" class="btn btn-primary" role="button">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </a>
        </p>

        <br />

    {% endif %}

{% endblock %}


{% block thead %}
    <th>ID</th>
    <th>{{ "trans.entity.tag" | trans }}</th>
    <th>{{ "trans.entity.application" | trans }}</th>
    <th>{{ "trans.entity.status" | trans }}</th>
    <th>{{ "trans.entity.createdBy" | trans }}</th>
    <th>{{ "trans.entity.updatedBy" | trans }}</th>
    <th></th>

{% endblock %}

{% block tbody %}
    {% for build in pagination.result %}
        <tr>
            <td>{{ build.id }}</td>
            <td>
                {{ build.currentTag }}
            </td>
            <td>
                {% if is_granted('ROLE_APPLICATION_SHOW') and build.application %}
                    <a class="btn btn-success" href="{{ path('ci_app_application_show', {application: build.application.id}) }}" role="button">
                        <span class="glyphicon glyphicon-phone" aria-hidden="true"></span>
                        {{ build.application }}
                    </a>

                    {{ APPLICATION_status_label(build.application) }}

                {% elseif build.application %}
                    {{ build.application }} {{ APPLICATION_status_label(build.application) }}

                {% else %}
                    ~
                {% endif %}
            </td>

            <td>{{ BUILD_status_label(build) }}</td>
            <td>{{ build.createdBy }} ({{ build.createdAt | date('d/m/Y H:i:s') }})</td>
            <td>{{ build.updatedBy }} ({{ build.updatedAt | date('d/m/Y H:i:s') }})</td>
            <td>
                {% include 'CIAppBundle::Build/actions.html.twig' with {show: true} %}
            </td>
        </tr>

    {% endfor %}

{% endblock %}

src/CI/AppBundle/Resources/views/Build/show.build.upload.html.twig
{% extends 'CIAppBundle::Default/crud/show.html.twig' %}

{% set back = path('ci_app_build_show', {build: buildUpload.build.id}) %}

{% block content_left %}
    <h2><span class="glyphicon glyphicon-upload"></span> {{ 'trans.title.upload' | trans }}</h2>

    <table class="table table-striped table-bordered table-hover table-condensed">
        <tbody>
            <tr>
                <td width="110px"><b>{{ 'trans.entity.targetPath' | trans }}</b></td>
                <td>{{ buildUpload.targetPath }}</td>
            </tr>

            <tr>
                <td><b>{{ 'trans.entity.value' | trans }}</b></td>
                <td><pre>{{ buildUpload.value }}</pre></td>
            </tr>
        </tbody>
    </table>

{% endblock %}

src/CI/AppBundle/Resources/views/Build/show.html.twig
{% extends 'CIAppBundle::Default/crud/show.html.twig' %}

{% set back = path('ci_app_build_index') %}

{% block content_left %}
    <h2><span class="glyphicon glyphicon-build" aria-hidden="true"></span> {{ 'trans.menu.build' | trans }}</h2> <br />

    <table class="table table-striped table-bordered table-hover table-condensed">
        <tbody>
            <tr>
                <td width="120px"><b>{{ 'trans.entity.name' | trans }}</b></td>
                <td>
                    {{ build.currentTag }}

                    {{ BUILD_status_label(build) }}
                </td>
            </tr>

            <tr>
                <td width="120px"><b>{{ 'trans.entity.application' | trans }}</b></td>
                <td>
                    {% if is_granted('ROLE_APPLICATION_SHOW') and build.application %}
                        <a class="btn btn-success" href="{{ path('ci_app_application_show', {application: build.application.id}) }}" role="button">
                            <span class="glyphicon glyphicon-phone" aria-hidden="true"></span>
                            {{ build.application }}
                        </a>

                        {{ APPLICATION_status_label(build.application) }}

                    {% elseif build.application %}
                        {{ build.application }} {{ APPLICATION_status_label(build.application) }}

                    {% else %}
                        ~
                    {% endif %}
                </td>
            </tr>

            <tr>
                <td width="120px"><b>{{ 'trans.entity.branch' | trans }}</b></td>
                <td>{{ build.branch }}</td>
            </tr>

            <tr>
                <td width="120px"><b>{{ 'trans.entity.repo' | trans }}</b></td>
                <td>{{ build.repo }}</td>
            </tr>

            <tr>
                <td width="120px"><b>{{ 'trans.entity.autoDeploy' | trans }}</b></td>
                <td>{% if build.autoDeploy %}{{ 'trans.message.yes' | trans }}{% else %}{{ 'trans.message.no' | trans }}{% endif %}</pre></td>
            </tr>

            <tr>
                <td width="120px"><b>{{ 'trans.entity.script' | trans }}</b></td>
                <td>{{ build.script }}</pre></td>
            </tr>

            <tr>
                <td width="110px"><b>{{ 'trans.entity.createdBy' | trans }}</b></td>
                <td>{{ build.createdBy }} ({{ build.createdAt | date('d/m/Y H:i:s') }})</td>
            </tr>

            <tr>
                <td width="110px"><b>{{ 'trans.entity.updatedBy' | trans }}</b></td>
                <td>{{ build.updatedBy }} ({{ build.updatedAt | date('d/m/Y H:i:s') }})</td>
            </tr>
        </tbody>
    </table>

{% endblock %}

{% block content_right %}
    {% include 'CIAppBundle::Build/show.tag.html.twig' %}

    {% include 'CIAppBundle::Build/show.upload.html.twig' %}

{% endblock %}

{% block actions %}
    <br />

    <table class="table table-striped table-bordered table-hover table-condensed">
        <tbody>
            <tr>
                <td width="110px"><b>{{ "trans.entity.response" | trans }}</b></td>
                <td><pre>{{ response }}</pre></td>
            </tr>
        </tbody>
    </table>

    <br />

    {% include 'CIAppBundle::Build/actions.html.twig' %}

{% endblock %}

src/CI/AppBundle/Resources/views/Build/show.tag.html.twig
<h2><span class="glyphicon glyphicon-picture"></span> {{ 'trans.title.tag' | trans }}</h2>

{% if build.tag | length %}
    <table class="table table-striped table-bordered table-hover table-condensed">
        <thead>
            <tr>
                <th>{{ "trans.entity.status" | trans }}</th>
                <th>{{ "trans.entity.repo" | trans }}</th>
                <th>{{ "trans.entity.tag" | trans }}</th>
                <th>{{ "trans.entity.branch" | trans }}</th>
                <th>{{ "trans.entity.createdAt" | trans }}</th>
                <th>{{ "trans.entity.builtAt" | trans }}</th>
                <th>{{ "trans.entity.buildQuantity" | trans }}</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for tag in build.tag %}
                <tr>
                    <td>{{ TAG_status_label(tag) }}</td>
                    <td>{{ tag.repo }}</td>
                    <td>{{ tag.name }}</td>
                    <td>{{ tag.branch }}@{{ tag.commit }}</td>
                    <td>{{ tag.createdAt | date('d/m/Y H:i:s') }}</td>
                    <td>{{ tag.builtAt | date('d/m/Y H:i:s') }}</td>
                    <td>{{ tag.buildQuantity }}</td>
                    <td>
                        {% if TAG_can_build(tag) %}
                            <a title="{{ 'trans.action.build' | trans }}" class="btn btn-primary" href="{{ path('ci_app_tag_build', {tag: tag.id}) }}" role="button">
                                <span class="glyphicon glyphicon-send" aria-hidden="true"></span>
                            </a>

                        {% endif %}

                        {% if TAG_can_delete(tag) %}
                            <a title="{{ 'trans.action.build' | trans }}" class="btn btn-danger" href="{{ path('ci_app_tag_delete', {tag: tag.id}) }}" role="button">
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                            </a>

                        {% endif %}
                    </td>
                </tr>

            {% endfor %}

        </tbody>
    </table>

{% else %}
    {{ MESSAGE_single('info', 'trans.message.tag.list.empty') }}

{% endif %}

src/CI/AppBundle/Resources/views/Build/show.upload.html.twig
<h2><span class="glyphicon glyphicon-upload"></span> {{ 'trans.title.upload' | trans }}</h2>

{% if build.buildUpload | length %}
    <table class="table table-striped table-bordered table-hover table-condensed">
        <thead>
            <tr>
                <th>{{ "trans.entity.targetPath" | trans }}</th>
                {% if is_granted('ROLE_BUILD_SHOW_UPLOAD') %}
                    <th>-</th>

                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for buildUpload in build.buildUpload %}
                <tr>
                    <td>{{ buildUpload.targetPath }}</td>
                    {% if is_granted('ROLE_BUILD_SHOW_UPLOAD') %}
                        <td>
                            <a title="{{ 'trans.action.show' | trans }}" class="btn btn-info" href="{{ path('ci_app_build_show_upload', {buildUpload: buildUpload.id}) }}" role="button">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            </a>
                        </td>

                    {% endif %}
                </tr>

            {% endfor %}

        </tbody>
    </table>

{% else %}
    {{ MESSAGE_single('info', 'trans.message.upload.list.empty') }}

{% endif %}